# -*- coding: utf-8 -*-
"""Copy of Copy_of_Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jVFtZM1g-dG4JHyR23hJIf6jZzXRSR7C
"""

import pandas as pd

# قراءة ملف البيانات
df = pd.read_csv('Predictive_Maintenance_dataset.csv', sep=';')

# عرض أول 5 صفوف
df.head()

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# قراءة ملف البيانات
df = pd.read_csv('Predictive_Maintenance_dataset_22.csv', sep=';')

# عرض أول 5 صفوف
print(df.head())

# اختيار المدخلات
X = df[['Failure',
        'Predictability',
        'Repeatability',
        'Operational_impact',
        'Sudden',
        'Severity',
        'Symptom_Duration']]

# تحويل Risk Score إلى أرقام
y = pd.to_numeric(df['Risk_Score'], errors='coerce')

# تحويل درجات الخطورة إلى تصنيفات
def classify(score):
    if score >= 8:
        return 'Critical'
    elif score >= 5:
        return 'Warning'
    else:
        return 'Normal'

y = y.apply(classify)

# تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# إنشاء النموذج
model = DecisionTreeClassifier()

# تدريب النموذج
model.fit(X_train, y_train)

# التنبؤ
predictions = model.predict(X_test)

# حساب الدقة
accuracy = accuracy_score(y_test, predictions)

# عرض النتائج
print("\nAI Model Accuracy:", accuracy)
print("Predictions:", predictions)

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': model.feature_importances_
})

feature_importance = feature_importance.sort_values(by='Importance', ascending=False)

print(feature_importance)

import matplotlib.pyplot as plt

# رسم أهم العوامل
plt.figure(figsize=(8,5))

plt.bar(
    feature_importance['Feature'],
    feature_importance['Importance']
)

plt.title('AI Feature Importance')
plt.xlabel('Factors')
plt.ylabel('Importance Score')

plt.xticks(rotation=45)

plt.show()

# بيانات جهاز جديد للتجربة

new_device = [[
    1,  # Failure
    3,  # Predictability
    3,  # Repeatability
    4,  # Operational_impact
    0,  # Sudden
    3,  # Severity
    7   # Symptom_Duration
]]

# توقع الحالة
prediction = model.predict(new_device)

print("Predicted AI Status:", prediction[0])

# تجربة حالة متوسطة الخطورة

new_device_warning = [[
    1,  # Failure
    2,  # Predictability
    2,  # Repeatability
    3,  # Operational_impact
    0,  # Sudden
    2,  # Severity
    7   # Symptom_Duration
]]

prediction_warning = model.predict(new_device_warning)

print("Predicted AI Status:", prediction_warning[0])

# تجربة حالة طبيعية

new_device_normal = [[
    0,  # Failure
    1,  # Predictability
    0,  # Repeatability
    0,  # Operational_impact
    0,  # Sudden
    0,  # Severity
    0   # Symptom_Duration
]]

prediction_normal = model.predict(new_device_normal)

print("Predicted AI Status:", prediction_normal[0])

from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

# تحويل التصنيفات إلى أرقام
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# تقسيم البيانات
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42
)

# إنشاء نموذج XGBoost
xgb_model = XGBClassifier()

# تدريب النموذج
xgb_model.fit(X_train, y_train)

# التنبؤ
xgb_predictions = xgb_model.predict(X_test)

# حساب الدقة
xgb_accuracy = accuracy_score(y_test, xgb_predictions)

print("XGBoost Accuracy:", xgb_accuracy)

# تحويل توقعات XGBoost من أرقام إلى أسماء الحالات
xgb_pred_labels = encoder.inverse_transform(xgb_predictions)

print("XGBoost Predictions:")
print(xgb_pred_labels)

import pandas as pd

xgb_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': xgb_model.feature_importances_
})

xgb_importance = xgb_importance.sort_values(by='Importance', ascending=False)

print(xgb_importance)

import matplotlib.pyplot as plt

# رسم أهمية العوامل في XGBoost
plt.figure(figsize=(8,5))

plt.bar(
    xgb_importance['Feature'],
    xgb_importance['Importance']
)

plt.title('XGBoost Feature Importance')
plt.xlabel('Factors')
plt.ylabel('Importance Score')

plt.xticks(rotation=45)

plt.show()
